### ISSUE TITLE
Exception when importing ebpf object file

### ISSUE THREAD

**Issue by amitschendel** [Nalen98/eBPF-for-Ghidra#13]
Hey! I am getting this error when trying to use the extension.
I have cloned the project to the extension folder of ghidra and then installed it.
Then, I tried importing a couple of different object files (eBPF ofc) but I always get this error.
It seems like some method is missing in the class but from a quick look in the code it seems the class has this function so I am not sure why it happens.
I am running it on mac arm64 cpu.
```
Receiver class ghidra.app.util.bin.format.elf.relocation.eBPF_ElfRelocationHandler does not define or inherit an implementation of the resolved method 'abstract ghidra.program.model.reloc.RelocationResult relocate(ghidra.app.util.bin.format.elf.relocation.ElfRelocationContext, ghidra.app.util.bin.format.elf.ElfRelocation, ghidra.program.model.address.Address)' of abstract class ghidra.app.util.bin.format.elf.relocation.ElfRelocationHandler.
java.lang.AbstractMethodError: Receiver class ghidra.app.util.bin.format.elf.relocation.eBPF_ElfRelocationHandler does not define or inherit an implementation of the resolved method 'abstract ghidra.program.model.reloc.RelocationResult relocate(ghidra.app.util.bin.format.elf.relocation.ElfRelocationContext, ghidra.app.util.bin.format.elf.ElfRelocation, ghidra.program.model.address.Address)' of abstract class ghidra.app.util.bin.format.elf.relocation.ElfRelocationHandler.
	at ghidra.app.util.bin.format.elf.relocation.ElfRelocationContext.processRelocation(ElfRelocationContext.java:112)
	at ghidra.app.util.opinion.ElfProgramBuilder.processRelocationTableEntries(ElfProgramBuilder.java:1054)
	at ghidra.app.util.opinion.ElfProgramBuilder.processRelocationTable(ElfProgramBuilder.java:953)
	at ghidra.app.util.opinion.ElfProgramBuilder.processRelocations(ElfProgramBuilder.java:888)
	at ghidra.app.util.opinion.ElfProgramBuilder.load(ElfProgramBuilder.java:173)
	at ghidra.app.util.opinion.ElfProgramBuilder.loadElf(ElfProgramBuilder.java:110)
	at ghidra.app.util.opinion.ElfLoader.load(ElfLoader.java:148)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:887)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:98)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:131)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:395)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:336)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by Nalen98** [comment]
Hi!
Sorry for the long delay.

I saw that you reported the issue to the official Ghidra repository: https://github.com/NationalSecurityAgency/ghidra/issues/6621. 
That was the right step, as the current eBPF-for-Ghidra repository has been included in Ghidra since May 2023. All the latest updates and fixes are available there.

The root of the problem was that eBPF module used an outdated Ghidra API related to ELF relocation handlers. It was refactored a few months ago, which was the main reason you couldn't successfully perform the import of ebpf object file.

I may archive this repository at some point in the future.   
Thank you for your activity!
